<a href="https://colab.research.google.com/github/iam-fern/Research/blob/main/ex_sampling_1000rep_n70_x6_sas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

import statistics as stats
import scipy.stats as ss
from scipy.stats import f_oneway
from scipy import stats
import scipy.stats as stats
import time
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/sampling_1000rep_n70_x6_sas.csv')
df

         rep  index         x1  ...             Y         y_hat         e_hat
0        0.0    0.0  15.054082  ... -6.454286e+06  2.565901e+07 -3.211330e+07
1        0.0    1.0  34.952603  ... -8.443636e+08 -5.241312e+06 -8.391223e+08
2        0.0    2.0  17.540057  ... -3.436448e+07 -1.221287e+07 -2.215161e+07
3        0.0    3.0  35.160251  ...  1.152211e+08  1.804217e+07  9.717896e+07
4        0.0    4.0  44.507887  ... -5.361096e+09 -3.144589e+07 -5.329650e+09
...      ...    ...        ...  ...           ...           ...           ...
69995  999.0   65.0  21.841009  ... -1.618884e+08  1.201104e+07 -1.738994e+08
69996  999.0   66.0  29.058554  ... -2.803241e+07 -1.666412e+07 -1.136829e+07
69997  999.0   67.0  28.627611  ... -3.393542e+08 -3.287193e+07 -3.064823e+08
69998  999.0   68.0  27.395968  ...  5.179927e+08 -1.011684e+07  5.281095e+08
69999  999.0   69.0  29.161093  ...  1.031113e+09 -1.873917e+07  1.049852e+09

[70000 rows x 9 columns]

In [3]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/sampling_1000rep_n70_x6_sas.csv', index_col=['rep', 'index'])
df

                    x1         x2  ...         y_hat         e_hat
rep   index                        ...
0.0   0.0    15.054082  11.269525  ...  2.565901e+07 -3.211330e+07
      1.0    34.952603  23.295228  ... -5.241312e+06 -8.391223e+08
      2.0    17.540057  24.740895  ... -1.221287e+07 -2.215161e+07
      3.0    35.160251  18.213491  ...  1.804217e+07  9.717896e+07
      4.0    44.507887  22.686051  ... -3.144589e+07 -5.329650e+09
...                ...        ...  ...           ...           ...
999.0 65.0   21.841009  19.350043  ...  1.201104e+07 -1.738994e+08
      66.0   29.058554  49.533739  ... -1.666412e+07 -1.136829e+07
      67.0   28.627611  33.797163  ... -3.287193e+07 -3.064823e+08
      68.0   27.395968  10.646612  ... -1.011684e+07  5.281095e+08
      69.0   29.161093  31.864708  ... -1.873917e+07  1.049852e+09

[70000 rows x 7 columns]

In [4]:
# ลบข้อมูลที่มี missing values
table = df.dropna()
table

                    x1         x2  ...         y_hat         e_hat
rep   index                        ...
0.0   0.0    15.054082  11.269525  ...  2.565901e+07 -3.211330e+07
      1.0    34.952603  23.295228  ... -5.241312e+06 -8.391223e+08
      2.0    17.540057  24.740895  ... -1.221287e+07 -2.215161e+07
      3.0    35.160251  18.213491  ...  1.804217e+07  9.717896e+07
      4.0    44.507887  22.686051  ... -3.144589e+07 -5.329650e+09
...                ...        ...  ...           ...           ...
999.0 65.0   21.841009  19.350043  ...  1.201104e+07 -1.738994e+08
      66.0   29.058554  49.533739  ... -1.666412e+07 -1.136829e+07
      67.0   28.627611  33.797163  ... -3.287193e+07 -3.064823e+08
      68.0   27.395968  10.646612  ... -1.011684e+07  5.281095e+08
      69.0   29.161093  31.864708  ... -1.873917e+07  1.049852e+09

[70000 rows x 7 columns]

In [5]:
table.reset_index(inplace=True)
table

         rep  index         x1  ...             Y         y_hat         e_hat
0        0.0    0.0  15.054082  ... -6.454286e+06  2.565901e+07 -3.211330e+07
1        0.0    1.0  34.952603  ... -8.443636e+08 -5.241312e+06 -8.391223e+08
2        0.0    2.0  17.540057  ... -3.436448e+07 -1.221287e+07 -2.215161e+07
3        0.0    3.0  35.160251  ...  1.152211e+08  1.804217e+07  9.717896e+07
4        0.0    4.0  44.507887  ... -5.361096e+09 -3.144589e+07 -5.329650e+09
...      ...    ...        ...  ...           ...           ...           ...
69995  999.0   65.0  21.841009  ... -1.618884e+08  1.201104e+07 -1.738994e+08
69996  999.0   66.0  29.058554  ... -2.803241e+07 -1.666412e+07 -1.136829e+07
69997  999.0   67.0  28.627611  ... -3.393542e+08 -3.287193e+07 -3.064823e+08
69998  999.0   68.0  27.395968  ...  5.179927e+08 -1.011684e+07  5.281095e+08
69999  999.0   69.0  29.161093  ...  1.031113e+09 -1.873917e+07  1.049852e+09

[70000 rows x 9 columns]

In [6]:
table.set_index(['rep', 'index'], inplace=True)

In [7]:
table

                    x1         x2  ...         y_hat         e_hat
rep   index                        ...
0.0   0.0    15.054082  11.269525  ...  2.565901e+07 -3.211330e+07
      1.0    34.952603  23.295228  ... -5.241312e+06 -8.391223e+08
      2.0    17.540057  24.740895  ... -1.221287e+07 -2.215161e+07
      3.0    35.160251  18.213491  ...  1.804217e+07  9.717896e+07
      4.0    44.507887  22.686051  ... -3.144589e+07 -5.329650e+09
...                ...        ...  ...           ...           ...
999.0 65.0   21.841009  19.350043  ...  1.201104e+07 -1.738994e+08
      66.0   29.058554  49.533739  ... -1.666412e+07 -1.136829e+07
      67.0   28.627611  33.797163  ... -3.287193e+07 -3.064823e+08
      68.0   27.395968  10.646612  ... -1.011684e+07  5.281095e+08
      69.0   29.161093  31.864708  ... -1.873917e+07  1.049852e+09

[70000 rows x 7 columns]

In [8]:
def get_result(run_replicate, percent_data):
    new_table = table.loc[run_replicate]

    # เรียง data จากน้อยไปมากตาม x1
    new_table_sort = new_table.sort_values('x1')

    new_table_sort.reset_index(inplace=True)

    #new_table_sort.drop(['index'], axis=1, inplace=True)


    # แบ่งข้อมูลกลุ่มที่ 1
    table1 = new_table_sort.iloc[:int(percent_data*new_table_sort.shape[0]) , :]
    # define respones variable
    y = table1['Y']
    # define predictor variable
    x = table1[['x1', 'x2', 'x3']]
    # add constant to predictor variable
    x = sm.add_constant(x)
    # fit linear regression model
    model1 = sm.OLS(y, x).fit()

    # หาค่า df กลุ่ม 1
    DF1 = model1.df_resid
    # หาค่า SSE1 : Residual sum of squares
    SSE1 = model1.ssr
    # หาค่า MSE1
    MSE1 = model1.mse_resid


    # แบ่งข้อมูลกลุ่มที่ 2
    table2 = new_table_sort.iloc[int((1-percent_data)*new_table_sort.shape[0]): , :]

    y = table2['Y']
    x = table2[['x1', 'x2', 'x3']]
    x = sm.add_constant(x)
    model2 = sm.OLS(y, x).fit()
    #print(model.summary())

    # หาค่า df กลุ่ม 2
    DF2 = model2.df_resid
    # หาค่า SSE2 : : Residual sum of squares
    SSE2 = model2.ssr
    # หาค่า MSE2
    MSE2 = model2.mse_resid

    # ค่าสถิติทดสอบ
    GQ_test = MSE2 / MSE1


    df2 = DF2
    df1 = DF1

    # คำนวณค่า p-value
    # sf(x, dfn, dfd, loc=0, scale=1) : Survival function (also defined as 1 - cdf, but sf is sometimes more accurate)
    two_tailed = 2.0*(1.0-(ss.f.cdf(GQ_test, df2, df1)))

    # pdf(x, dfn, dfd, loc=0, scale=1) : Probability density function
    p_greater = ss.f.cdf(GQ_test, df2, df1)
    
    return df2, df1, SSE2, SSE1, MSE2, MSE1, GQ_test, two_tailed, p_greater
    

    # เปรียบเทียบค่า p-value กับค่า alpha
    # Homoscedasticity : 0
    # Heteroscedasticity : 1
    #if p_value < alpha:
        #result_test='Reject005=0 : Heteroscedasticity '
        #result_test01=1
    #else:
        #result_test='Reject005=1 : Homoscedasticity '
        #result_test01=0
    
    #return df1, df2, SSE1, SSE2, MSE1, MSE2, GQ_test, result_test, p_value, result_test01


# สร้าง list ของ replicates
list_replicate=list({i[0] for i in table.index})
list_replicate.sort()

# สร้าง list เพื่อเก็บค่า ทุกรอบที่ run
list_df1=[]
list_df2=[]
list_SSE1=[]
list_SSE2=[]
list_MSE1=[]
list_MSE2=[]
list_GQ_test=[]
#list_result_test=[]
list_two_tailed=[]
list_p_greater=[]
#list_result_test01=[]


# กำหนด % การแบ่งข้อมูล
percent_data=0.4

# ใช้ for loop สำหรับการ run ทุก replicates
for run_replicate in list_replicate:
    #DF1, DF2, SSE1, SSE2, M_SSE1, M_SSE2, GQ_test, result_test=get_result(run_replicate, percent_data)
    df1, df2, SSE1, SSE2, MSE1, MSE2, GQ_test, two_tailed, p_greater=get_result(run_replicate, percent_data)
    list_df1.append(df1)
    list_SSE1.append(SSE1)
    list_df2.append(df2)
    list_SSE2.append(SSE2)
    list_MSE1.append(MSE1)
    list_MSE2.append(MSE2)
    list_GQ_test.append(GQ_test)
    #list_result_test.append(result_test)
    list_two_tailed.append(two_tailed)
    list_p_greater.append(p_greater)
    #list_result_test01.append(result_test01)

In [9]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
result=pd.DataFrame({"Replicate":list_replicate, "df1":list_df1, "df2":list_df2, "SSE1":list_SSE1,
                     "SSE2":list_SSE2, "MSE1":list_MSE1, "MSE2":list_MSE2,
                     "GQ_test":list_GQ_test, "two_tailed":list_two_tailed, "greater":list_p_greater})
result.set_index(['Replicate'], inplace=True)
result=result[(result["two_tailed"]<=1) & (result["greater"]<=1)]
result["Result_test"]=result["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")

result.astype(str)

            df1   df2                    SSE1                    SSE2                    MSE1                    MSE2             GQ_test             two_tailed             greater                       Result_test
Replicate
0.0        24.0  24.0  1.1658492423387905e+21  2.4221133324156332e+16   4.857705176411627e+19      1009213888506513.9  48133.554558987555  2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity
1.0        24.0  24.0  1.2107676026605797e+21  1.9647247295753894e+17   5.044865011085749e+19      8186353039897456.0   6162.530477856037  2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity
2.0        24.0  24.0  1.4531075482153808e+21   2.708070807208309e+18   6.054614784230753e+19  1.1283628363367955e+17   536.5840303538287  2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity
3.0        24.0  24.0  1.4929081800709235e+21   1.172291443610876e+17   6.220450750295514e+19      4884547681711983.0  12734.957575673232  2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity
4.0        24.0  24.0  1.1668962159129328e+21   2.790990513925966e+17  4.8620675663038865e+19  1.1629127141358192e+16   4180.939383672466  2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity
...         ...   ...                     ...                     ...                     ...                     ...                 ...                    ...                 ...                               ...
995.0      24.0  24.0   8.903805233717844e+20  3.4446941781533436e+16  3.7099188473824354e+19      1435289240897226.5  25847.883072427234  2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity
996.0      24.0  24.0   5.184136148475514e+20   3.735582238865294e+16   2.160056728531464e+19      1556492599527206.0  13877.719233535672  2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity
997.0      24.0  24.0   1.067622589257147e+21   6.047904753237719e+16   4.448427455238112e+19      2519960313849049.5   17652.76790587021  2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity
998.0      24.0  24.0   9.681184343819724e+20   5.007632408195691e+17   4.033826809924885e+19   2.086513503414871e+16  1933.2857435731728  2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity
999.0      24.0  24.0  1.7676944910934926e+21  1.5647150023480304e+17   7.365393712889552e+19      6519645843116793.0   11297.22977309522  2.220446049250313e-16  0.9999999999999999  Reject005=0 : Heteroscedasticity

[1000 rows x 10 columns]

In [10]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
result=pd.DataFrame({"Replicate":list_replicate, "df1":list_df1, "df2":list_df2, "SSE1":list_SSE1,
                     "SSE2":list_SSE2, "MSE1":list_MSE1, "MSE2":list_MSE2,
                     "GQ_test":list_GQ_test, "two_tailed":list_two_tailed, "greater":list_p_greater})
result.set_index(['Replicate'], inplace=True)

result['two_tailed_new']=result[["two_tailed","greater"]].apply(lambda value: value[0] if value[0]<0.5 else 2*value[1], axis=1)
result["Result_test"]=result["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")
result_show=result.drop(columns=["two_tailed", "greater"])
result_show.astype(str)

            df1   df2                    SSE1                    SSE2                    MSE1                    MSE2             GQ_test         two_tailed_new                       Result_test
Replicate
0.0        24.0  24.0  1.1658492423387905e+21  2.4221133324156332e+16   4.857705176411627e+19      1009213888506513.9  48133.554558987555  2.220446049250313e-16  Reject005=0 : Heteroscedasticity
1.0        24.0  24.0  1.2107676026605797e+21  1.9647247295753894e+17   5.044865011085749e+19      8186353039897456.0   6162.530477856037  2.220446049250313e-16  Reject005=0 : Heteroscedasticity
2.0        24.0  24.0  1.4531075482153808e+21   2.708070807208309e+18   6.054614784230753e+19  1.1283628363367955e+17   536.5840303538287  2.220446049250313e-16  Reject005=0 : Heteroscedasticity
3.0        24.0  24.0  1.4929081800709235e+21   1.172291443610876e+17   6.220450750295514e+19      4884547681711983.0  12734.957575673232  2.220446049250313e-16  Reject005=0 : Heteroscedasticity
4.0        24.0  24.0  1.1668962159129328e+21   2.790990513925966e+17  4.8620675663038865e+19  1.1629127141358192e+16   4180.939383672466  2.220446049250313e-16  Reject005=0 : Heteroscedasticity
...         ...   ...                     ...                     ...                     ...                     ...                 ...                    ...                               ...
995.0      24.0  24.0   8.903805233717844e+20  3.4446941781533436e+16  3.7099188473824354e+19      1435289240897226.5  25847.883072427234  2.220446049250313e-16  Reject005=0 : Heteroscedasticity
996.0      24.0  24.0   5.184136148475514e+20   3.735582238865294e+16   2.160056728531464e+19      1556492599527206.0  13877.719233535672  2.220446049250313e-16  Reject005=0 : Heteroscedasticity
997.0      24.0  24.0   1.067622589257147e+21   6.047904753237719e+16   4.448427455238112e+19      2519960313849049.5   17652.76790587021  2.220446049250313e-16  Reject005=0 : Heteroscedasticity
998.0      24.0  24.0   9.681184343819724e+20   5.007632408195691e+17   4.033826809924885e+19   2.086513503414871e+16  1933.2857435731728  2.220446049250313e-16  Reject005=0 : Heteroscedasticity
999.0      24.0  24.0  1.7676944910934926e+21  1.5647150023480304e+17   7.365393712889552e+19      6519645843116793.0   11297.22977309522  2.220446049250313e-16  Reject005=0 : Heteroscedasticity

[1000 rows x 9 columns]

In [11]:
result_show['Result_test'].value_counts()

Reject005=0 : Heteroscedasticity    1000
Name: Result_test, dtype: int64