<a href="https://colab.research.google.com/github/iam-fern/Research/blob/main/ex_sampling_1000rep_n20_x6_sas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

import statistics as stats
import scipy.stats as ss
from scipy.stats import f_oneway
from scipy import stats
import scipy.stats as stats
import time
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/sampling_1000rep_n20_x6_sas.csv')
df

         rep  index         x1  ...             Y         y_hat         e_hat
0        0.0    0.0  45.434458  ... -5.128723e+09  2.517003e+07 -5.153893e+09
1        0.0    1.0  26.559493  ... -4.163185e+08  3.245325e+07 -4.487718e+08
2        0.0    2.0  40.852372  ... -7.631340e+09  4.076199e+07 -7.672102e+09
3        0.0    3.0  33.195003  ...  4.762832e+08  2.729472e+05  4.760103e+08
4        0.0    4.0  47.245321  ...  1.016395e+10  7.742754e+07  1.008653e+10
...      ...    ...        ...  ...           ...           ...           ...
19995  999.0   15.0  19.317492  ... -7.111128e+07  2.949752e+06 -7.406103e+07
19996  999.0   16.0  19.139182  ...  1.249659e+07 -1.874484e+07  3.124144e+07
19997  999.0   17.0  39.393803  ...  3.000370e+09  5.189096e+07  2.948479e+09
19998  999.0   18.0  17.721641  ... -2.419867e+07 -3.633056e+07  1.213189e+07
19999  999.0   19.0  19.584374  ... -2.435902e+07 -7.352142e+06 -1.700688e+07

[20000 rows x 9 columns]

In [3]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/sampling_1000rep_n20_x6_sas.csv', index_col=['rep', 'index'])
df

                    x1         x2  ...         y_hat         e_hat
rep   index                        ...
0.0   0.0    45.434458  48.093789  ...  2.517003e+07 -5.153893e+09
      1.0    26.559493  16.536534  ...  3.245325e+07 -4.487718e+08
      2.0    40.852372  34.324820  ...  4.076199e+07 -7.672102e+09
      3.0    33.195003  43.436660  ...  2.729472e+05  4.760103e+08
      4.0    47.245321  21.336256  ...  7.742754e+07  1.008653e+10
...                ...        ...  ...           ...           ...
999.0 15.0   19.317492  20.586124  ...  2.949752e+06 -7.406103e+07
      16.0   19.139182  33.264554  ... -1.874484e+07  3.124144e+07
      17.0   39.393803  25.755468  ...  5.189096e+07  2.948479e+09
      18.0   17.721641  40.783730  ... -3.633056e+07  1.213189e+07
      19.0   19.584374  28.628434  ... -7.352142e+06 -1.700688e+07

[20000 rows x 7 columns]

In [4]:
# ลบข้อมูลที่มี missing values
table = df.dropna()
table

                    x1         x2  ...         y_hat         e_hat
rep   index                        ...
0.0   0.0    45.434458  48.093789  ...  2.517003e+07 -5.153893e+09
      1.0    26.559493  16.536534  ...  3.245325e+07 -4.487718e+08
      2.0    40.852372  34.324820  ...  4.076199e+07 -7.672102e+09
      3.0    33.195003  43.436660  ...  2.729472e+05  4.760103e+08
      4.0    47.245321  21.336256  ...  7.742754e+07  1.008653e+10
...                ...        ...  ...           ...           ...
999.0 15.0   19.317492  20.586124  ...  2.949752e+06 -7.406103e+07
      16.0   19.139182  33.264554  ... -1.874484e+07  3.124144e+07
      17.0   39.393803  25.755468  ...  5.189096e+07  2.948479e+09
      18.0   17.721641  40.783730  ... -3.633056e+07  1.213189e+07
      19.0   19.584374  28.628434  ... -7.352142e+06 -1.700688e+07

[20000 rows x 7 columns]

In [5]:
table.reset_index(inplace=True)
table

         rep  index         x1  ...             Y         y_hat         e_hat
0        0.0    0.0  45.434458  ... -5.128723e+09  2.517003e+07 -5.153893e+09
1        0.0    1.0  26.559493  ... -4.163185e+08  3.245325e+07 -4.487718e+08
2        0.0    2.0  40.852372  ... -7.631340e+09  4.076199e+07 -7.672102e+09
3        0.0    3.0  33.195003  ...  4.762832e+08  2.729472e+05  4.760103e+08
4        0.0    4.0  47.245321  ...  1.016395e+10  7.742754e+07  1.008653e+10
...      ...    ...        ...  ...           ...           ...           ...
19995  999.0   15.0  19.317492  ... -7.111128e+07  2.949752e+06 -7.406103e+07
19996  999.0   16.0  19.139182  ...  1.249659e+07 -1.874484e+07  3.124144e+07
19997  999.0   17.0  39.393803  ...  3.000370e+09  5.189096e+07  2.948479e+09
19998  999.0   18.0  17.721641  ... -2.419867e+07 -3.633056e+07  1.213189e+07
19999  999.0   19.0  19.584374  ... -2.435902e+07 -7.352142e+06 -1.700688e+07

[20000 rows x 9 columns]

In [6]:
table.set_index(['rep', 'index'], inplace=True)

In [7]:
table

                    x1         x2  ...         y_hat         e_hat
rep   index                        ...
0.0   0.0    45.434458  48.093789  ...  2.517003e+07 -5.153893e+09
      1.0    26.559493  16.536534  ...  3.245325e+07 -4.487718e+08
      2.0    40.852372  34.324820  ...  4.076199e+07 -7.672102e+09
      3.0    33.195003  43.436660  ...  2.729472e+05  4.760103e+08
      4.0    47.245321  21.336256  ...  7.742754e+07  1.008653e+10
...                ...        ...  ...           ...           ...
999.0 15.0   19.317492  20.586124  ...  2.949752e+06 -7.406103e+07
      16.0   19.139182  33.264554  ... -1.874484e+07  3.124144e+07
      17.0   39.393803  25.755468  ...  5.189096e+07  2.948479e+09
      18.0   17.721641  40.783730  ... -3.633056e+07  1.213189e+07
      19.0   19.584374  28.628434  ... -7.352142e+06 -1.700688e+07

[20000 rows x 7 columns]

In [8]:
def get_result(run_replicate, percent_data):
    new_table = table.loc[run_replicate]

    # เรียง data จากน้อยไปมากตาม x1
    new_table_sort = new_table.sort_values('x1')

    new_table_sort.reset_index(inplace=True)

    #new_table_sort.drop(['index'], axis=1, inplace=True)


    # แบ่งข้อมูลกลุ่มที่ 1
    table1 = new_table_sort.iloc[:int(percent_data*new_table_sort.shape[0]) , :]
    # define respones variable
    y = table1['Y']
    # define predictor variable
    x = table1[['x1', 'x2', 'x3']]
    # add constant to predictor variable
    x = sm.add_constant(x)
    # fit linear regression model
    model1 = sm.OLS(y, x).fit()

    # หาค่า df กลุ่ม 1
    DF1 = model1.df_resid
    # หาค่า SSE1 : Residual sum of squares
    SSE1 = model1.ssr
    # หาค่า MSE1
    MSE1 = model1.mse_resid


    # แบ่งข้อมูลกลุ่มที่ 2
    table2 = new_table_sort.iloc[int((1-percent_data)*new_table_sort.shape[0]): , :]

    y = table2['Y']
    x = table2[['x1', 'x2', 'x3']]
    x = sm.add_constant(x)
    model2 = sm.OLS(y, x).fit()
    #print(model.summary())

    # หาค่า df กลุ่ม 2
    DF2 = model2.df_resid
    # หาค่า SSE2 : : Residual sum of squares
    SSE2 = model2.ssr
    # หาค่า MSE2
    MSE2 = model2.mse_resid

    # ค่าสถิติทดสอบ
    GQ_test = MSE2 / MSE1


    df2 = DF2
    df1 = DF1

    # คำนวณค่า p-value
    # sf(x, dfn, dfd, loc=0, scale=1) : Survival function (also defined as 1 - cdf, but sf is sometimes more accurate)
    two_tailed = 2.0*(1.0-(ss.f.cdf(GQ_test, df2, df1)))

    # pdf(x, dfn, dfd, loc=0, scale=1) : Probability density function
    p_greater = ss.f.cdf(GQ_test, df2, df1)
    
    return df2, df1, SSE2, SSE1, MSE2, MSE1, GQ_test, two_tailed, p_greater
    

    # เปรียบเทียบค่า p-value กับค่า alpha
    # Homoscedasticity : 0
    # Heteroscedasticity : 1
    #if p_value < alpha:
        #result_test='Reject005=0 : Heteroscedasticity '
        #result_test01=1
    #else:
        #result_test='Reject005=1 : Homoscedasticity '
        #result_test01=0
    
    #return df1, df2, SSE1, SSE2, MSE1, MSE2, GQ_test, result_test, p_value, result_test01


# สร้าง list ของ replicates
list_replicate=list({i[0] for i in table.index})
list_replicate.sort()

# สร้าง list เพื่อเก็บค่า ทุกรอบที่ run
list_df1=[]
list_df2=[]
list_SSE1=[]
list_SSE2=[]
list_MSE1=[]
list_MSE2=[]
list_GQ_test=[]
#list_result_test=[]
list_two_tailed=[]
list_p_greater=[]
#list_result_test01=[]


# กำหนด % การแบ่งข้อมูล
percent_data=0.4

# ใช้ for loop สำหรับการ run ทุก replicates
for run_replicate in list_replicate:
    #DF1, DF2, SSE1, SSE2, M_SSE1, M_SSE2, GQ_test, result_test=get_result(run_replicate, percent_data)
    df1, df2, SSE1, SSE2, MSE1, MSE2, GQ_test, two_tailed, p_greater=get_result(run_replicate, percent_data)
    list_df1.append(df1)
    list_SSE1.append(SSE1)
    list_df2.append(df2)
    list_SSE2.append(SSE2)
    list_MSE1.append(MSE1)
    list_MSE2.append(MSE2)
    list_GQ_test.append(GQ_test)
    #list_result_test.append(result_test)
    list_two_tailed.append(two_tailed)
    list_p_greater.append(p_greater)
    #list_result_test01.append(result_test01)

In [9]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
result=pd.DataFrame({"Replicate":list_replicate, "df1":list_df1, "df2":list_df2, "SSE1":list_SSE1,
                     "SSE2":list_SSE2, "MSE1":list_MSE1, "MSE2":list_MSE2,
                     "GQ_test":list_GQ_test, "two_tailed":list_two_tailed, "greater":list_p_greater})
result.set_index(['Replicate'], inplace=True)
result=result[(result["two_tailed"]<=1) & (result["greater"]<=1)]
result["Result_test"]=result["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")

result.astype(str)

           df1  df2                    SSE1                    SSE2                    MSE1                    MSE2             GQ_test              two_tailed             greater                       Result_test
Replicate
0.0        4.0  4.0   5.089552293749993e+20   7.724314134788549e+16  1.2723880734374982e+20  1.9310785336971372e+16   6589.002214226129   1.381453249571507e-07  0.9999999309273375  Reject005=0 : Heteroscedasticity
1.0        4.0  4.0   8.133987930151576e+19    2.89029603349887e+17   2.033496982537894e+19   7.225740083747174e+16   281.4240422391929   7.504496335331012e-05  0.9999624775183233  Reject005=0 : Heteroscedasticity
2.0        4.0  4.0   2.704144042746824e+20   4.663821418716013e+18    6.76036010686706e+19  1.1659553546790031e+18   57.98129473600849   0.0017052413493303664  0.9991473793253348  Reject005=0 : Heteroscedasticity
3.0        4.0  4.0  2.0955918000432487e+20      2744033854606172.0   5.238979500108122e+19       686008463651543.0   76369.02134153922  1.0287306562162257e-09  0.9999999994856347  Reject005=0 : Heteroscedasticity
4.0        4.0  4.0   4.102358421161446e+19   8.701011871228309e+16  1.0255896052903614e+19  2.1752529678070772e+16  471.48061419462493   2.683922944002326e-05    0.99998658038528  Reject005=0 : Heteroscedasticity
...        ...  ...                     ...                     ...                     ...                     ...                 ...                     ...                 ...                               ...
995.0      4.0  4.0  2.1802750935882993e+20   2.528877227585493e+16   5.450687733970748e+19      6322193068963732.0   8621.514203241768   8.069559598311571e-08   0.999999959652202  Reject005=0 : Heteroscedasticity
996.0      4.0  4.0   1.617665734201487e+20  1.4023132413800754e+16   4.044164335503717e+19      3505783103450188.5   11535.69463987571   4.507786699470273e-08  0.9999999774610665  Reject005=0 : Heteroscedasticity
997.0      4.0  4.0   1.609096677718822e+20  1.1559174995043984e+16   4.022741694297055e+19      2889793748760996.0  13920.514901874269  3.0956899710332664e-08  0.9999999845215501  Reject005=0 : Heteroscedasticity
998.0      4.0  4.0   1.088904831302026e+20      126660433741744.12   2.722262078255065e+19       31665108435436.03   859704.0126376499   8.117950756059145e-12   0.999999999995941  Reject005=0 : Heteroscedasticity
999.0      4.0  4.0   1.697663268218892e+20      3539244979900063.5    4.24415817054723e+19       884811244975015.9  47966.819981668195     2.6076256709473e-09  0.9999999986961872  Reject005=0 : Heteroscedasticity

[1000 rows x 10 columns]

In [10]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
result=pd.DataFrame({"Replicate":list_replicate, "df1":list_df1, "df2":list_df2, "SSE1":list_SSE1,
                     "SSE2":list_SSE2, "MSE1":list_MSE1, "MSE2":list_MSE2,
                     "GQ_test":list_GQ_test, "two_tailed":list_two_tailed, "greater":list_p_greater})
result.set_index(['Replicate'], inplace=True)

result['two_tailed_new']=result[["two_tailed","greater"]].apply(lambda value: value[0] if value[0]<0.5 else 2*value[1], axis=1)
result["Result_test"]=result["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")
result_show=result.drop(columns=["two_tailed", "greater"])
result_show.astype(str)

           df1  df2                    SSE1                    SSE2                    MSE1                    MSE2             GQ_test          two_tailed_new                       Result_test
Replicate
0.0        4.0  4.0   5.089552293749993e+20   7.724314134788549e+16  1.2723880734374982e+20  1.9310785336971372e+16   6589.002214226129   1.381453249571507e-07  Reject005=0 : Heteroscedasticity
1.0        4.0  4.0   8.133987930151576e+19    2.89029603349887e+17   2.033496982537894e+19   7.225740083747174e+16   281.4240422391929   7.504496335331012e-05  Reject005=0 : Heteroscedasticity
2.0        4.0  4.0   2.704144042746824e+20   4.663821418716013e+18    6.76036010686706e+19  1.1659553546790031e+18   57.98129473600849   0.0017052413493303664  Reject005=0 : Heteroscedasticity
3.0        4.0  4.0  2.0955918000432487e+20      2744033854606172.0   5.238979500108122e+19       686008463651543.0   76369.02134153922  1.0287306562162257e-09  Reject005=0 : Heteroscedasticity
4.0        4.0  4.0   4.102358421161446e+19   8.701011871228309e+16  1.0255896052903614e+19  2.1752529678070772e+16  471.48061419462493   2.683922944002326e-05  Reject005=0 : Heteroscedasticity
...        ...  ...                     ...                     ...                     ...                     ...                 ...                     ...                               ...
995.0      4.0  4.0  2.1802750935882993e+20   2.528877227585493e+16   5.450687733970748e+19      6322193068963732.0   8621.514203241768   8.069559598311571e-08  Reject005=0 : Heteroscedasticity
996.0      4.0  4.0   1.617665734201487e+20  1.4023132413800754e+16   4.044164335503717e+19      3505783103450188.5   11535.69463987571   4.507786699470273e-08  Reject005=0 : Heteroscedasticity
997.0      4.0  4.0   1.609096677718822e+20  1.1559174995043984e+16   4.022741694297055e+19      2889793748760996.0  13920.514901874269  3.0956899710332664e-08  Reject005=0 : Heteroscedasticity
998.0      4.0  4.0   1.088904831302026e+20      126660433741744.12   2.722262078255065e+19       31665108435436.03   859704.0126376499   8.117950756059145e-12  Reject005=0 : Heteroscedasticity
999.0      4.0  4.0   1.697663268218892e+20      3539244979900063.5    4.24415817054723e+19       884811244975015.9  47966.819981668195     2.6076256709473e-09  Reject005=0 : Heteroscedasticity

[1000 rows x 9 columns]

In [11]:
result_show['Result_test'].value_counts()

Reject005=0 : Heteroscedasticity    998
Reject005=1 : Homoscedasticity        2
Name: Result_test, dtype: int64