<a href="https://colab.research.google.com/github/iam-fern/Research/blob/main/ex_sampling_1000rep_n20_x4_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

import statistics as stats
import scipy.stats as ss
from scipy.stats import f_oneway
from scipy import stats
import scipy.stats as stats
import time
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/sampling_1000rep_n20_x4_2020.csv')
df

         rep  index       Xt1  ...          Y      y_hat     e_hat
0        0.0    0.0 -0.563151  ...   3.972090   3.787383  0.184707
1        0.0    1.0 -0.296755  ...   3.727457   3.567835  0.159622
2        0.0    2.0 -0.116487  ...  -1.342117  -1.378023  0.035905
3        0.0    3.0  0.621232  ...  -7.129093   2.452775 -9.581869
4        0.0    4.0  0.242119  ...   3.849033   3.745353  0.103680
...      ...    ...       ...  ...        ...        ...       ...
19995  999.0   15.0  0.883817  ...  14.830122  10.452450  4.377672
19996  999.0   16.0 -0.376627  ...   5.906781   5.714631  0.192151
19997  999.0   17.0  0.266842  ...  -4.035187   2.794325 -6.829512
19998  999.0   18.0  0.500518  ...   4.518583   4.466384  0.052199
19999  999.0   19.0 -0.830706  ...   7.184683   4.752370  2.432313

[20000 rows x 9 columns]

In [3]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/sampling_1000rep_n20_x4_2020.csv', index_col=['rep', 'index'])
df

                  Xt1       Xt2       Xt3  ...          Y      y_hat     e_hat
rep   index                                ...
0.0   0.0   -0.563151  0.283993 -0.060051  ...   3.972090   3.787383  0.184707
      1.0   -0.296755 -0.231266  0.051581  ...   3.727457   3.567835  0.159622
      2.0   -0.116487 -1.049339 -1.035387  ...  -1.342117  -1.378023  0.035905
      3.0    0.621232 -1.862679  0.275983  ...  -7.129093   2.452775 -9.581869
      4.0    0.242119 -0.027951 -0.057191  ...   3.849033   3.745353  0.103680
...               ...       ...       ...  ...        ...        ...       ...
999.0 15.0   0.883817  1.156202  1.261852  ...  14.830122  10.452450  4.377672
      16.0  -0.376627 -0.401335  0.738696  ...   5.906781   5.714631  0.192151
      17.0   0.266842  1.838888 -1.093791  ...  -4.035187   2.794325 -6.829512
      18.0   0.500518  0.473412 -0.095173  ...   4.518583   4.466384  0.052199
      19.0  -0.830706 -1.192900  0.854872  ...   7.184683   4.752370  2.432313

[20000 rows x 7 columns]

In [4]:
# ลบข้อมูลที่มี missing values
table = df.dropna()
table

                  Xt1       Xt2       Xt3  ...          Y      y_hat     e_hat
rep   index                                ...
0.0   0.0   -0.563151  0.283993 -0.060051  ...   3.972090   3.787383  0.184707
      1.0   -0.296755 -0.231266  0.051581  ...   3.727457   3.567835  0.159622
      2.0   -0.116487 -1.049339 -1.035387  ...  -1.342117  -1.378023  0.035905
      3.0    0.621232 -1.862679  0.275983  ...  -7.129093   2.452775 -9.581869
      4.0    0.242119 -0.027951 -0.057191  ...   3.849033   3.745353  0.103680
...               ...       ...       ...  ...        ...        ...       ...
999.0 15.0   0.883817  1.156202  1.261852  ...  14.830122  10.452450  4.377672
      16.0  -0.376627 -0.401335  0.738696  ...   5.906781   5.714631  0.192151
      17.0   0.266842  1.838888 -1.093791  ...  -4.035187   2.794325 -6.829512
      18.0   0.500518  0.473412 -0.095173  ...   4.518583   4.466384  0.052199
      19.0  -0.830706 -1.192900  0.854872  ...   7.184683   4.752370  2.432313

[20000 rows x 7 columns]

In [5]:
table.reset_index(inplace=True)
table

         rep  index       Xt1  ...          Y      y_hat     e_hat
0        0.0    0.0 -0.563151  ...   3.972090   3.787383  0.184707
1        0.0    1.0 -0.296755  ...   3.727457   3.567835  0.159622
2        0.0    2.0 -0.116487  ...  -1.342117  -1.378023  0.035905
3        0.0    3.0  0.621232  ...  -7.129093   2.452775 -9.581869
4        0.0    4.0  0.242119  ...   3.849033   3.745353  0.103680
...      ...    ...       ...  ...        ...        ...       ...
19995  999.0   15.0  0.883817  ...  14.830122  10.452450  4.377672
19996  999.0   16.0 -0.376627  ...   5.906781   5.714631  0.192151
19997  999.0   17.0  0.266842  ...  -4.035187   2.794325 -6.829512
19998  999.0   18.0  0.500518  ...   4.518583   4.466384  0.052199
19999  999.0   19.0 -0.830706  ...   7.184683   4.752370  2.432313

[20000 rows x 9 columns]

In [6]:
table.set_index(['rep', 'index'], inplace=True)

In [7]:
table

                  Xt1       Xt2       Xt3  ...          Y      y_hat     e_hat
rep   index                                ...
0.0   0.0   -0.563151  0.283993 -0.060051  ...   3.972090   3.787383  0.184707
      1.0   -0.296755 -0.231266  0.051581  ...   3.727457   3.567835  0.159622
      2.0   -0.116487 -1.049339 -1.035387  ...  -1.342117  -1.378023  0.035905
      3.0    0.621232 -1.862679  0.275983  ...  -7.129093   2.452775 -9.581869
      4.0    0.242119 -0.027951 -0.057191  ...   3.849033   3.745353  0.103680
...               ...       ...       ...  ...        ...        ...       ...
999.0 15.0   0.883817  1.156202  1.261852  ...  14.830122  10.452450  4.377672
      16.0  -0.376627 -0.401335  0.738696  ...   5.906781   5.714631  0.192151
      17.0   0.266842  1.838888 -1.093791  ...  -4.035187   2.794325 -6.829512
      18.0   0.500518  0.473412 -0.095173  ...   4.518583   4.466384  0.052199
      19.0  -0.830706 -1.192900  0.854872  ...   7.184683   4.752370  2.432313

[20000 rows x 7 columns]

In [8]:
def get_result(run_replicate, percent_data):
    new_table = table.loc[run_replicate]

    # เรียง data จากน้อยไปมากตาม x1
    new_table_sort = new_table.sort_values('Xt2')

    new_table_sort.reset_index(inplace=True)

    #new_table_sort.drop(['index'], axis=1, inplace=True)


    # แบ่งข้อมูลกลุ่มที่ 1
    table1 = new_table_sort.iloc[:int(percent_data*new_table_sort.shape[0]) , :]
    # define respones variable
    y = table1['Y']
    # define predictor variable
    x = table1[['Xt1', 'Xt2', 'Xt3']]
    # add constant to predictor variable
    x = sm.add_constant(x)
    # fit linear regression model
    model1 = sm.OLS(y, x).fit()

    # หาค่า df กลุ่ม 1
    DF1 = model1.df_resid
    # หาค่า SSE1 : Residual sum of squares
    SSE1 = model1.ssr
    # หาค่า MSE1
    MSE1 = model1.mse_resid


    # แบ่งข้อมูลกลุ่มที่ 2
    table2 = new_table_sort.iloc[int((1-percent_data)*new_table_sort.shape[0]): , :]

    y = table2['Y']
    x = table2[['Xt1', 'Xt2', 'Xt3']]
    x = sm.add_constant(x)
    model2 = sm.OLS(y, x).fit()
    #print(model.summary())

    # หาค่า df กลุ่ม 2
    DF2 = model2.df_resid
    # หาค่า SSE2 : : Residual sum of squares
    SSE2 = model2.ssr
    # หาค่า MSE2
    MSE2 = model2.mse_resid

    # ค่าสถิติทดสอบ
    GQ_test = MSE2 / MSE1


    df2 = DF2
    df1 = DF1

    # คำนวณค่า p-value
    # sf(x, dfn, dfd, loc=0, scale=1) : Survival function (also defined as 1 - cdf, but sf is sometimes more accurate)
    two_tailed = 2.0*(1.0-(ss.f.cdf(GQ_test, df2, df1)))

    # pdf(x, dfn, dfd, loc=0, scale=1) : Probability density function
    p_greater = ss.f.cdf(GQ_test, df2, df1)
    
    return df2, df1, SSE2, SSE1, MSE2, MSE1, GQ_test, two_tailed, p_greater
    

    # เปรียบเทียบค่า p-value กับค่า alpha
    # Homoscedasticity : 0
    # Heteroscedasticity : 1
    #if p_value < alpha:
        #result_test='Reject005=0 : Heteroscedasticity '
        #result_test01=1
    #else:
        #result_test='Reject005=1 : Homoscedasticity '
        #result_test01=0
    
    #return df1, df2, SSE1, SSE2, MSE1, MSE2, GQ_test, result_test, p_value, result_test01


# สร้าง list ของ replicates
list_replicate=list({i[0] for i in table.index})
list_replicate.sort()

# สร้าง list เพื่อเก็บค่า ทุกรอบที่ run
list_df1=[]
list_df2=[]
list_SSE1=[]
list_SSE2=[]
list_MSE1=[]
list_MSE2=[]
list_GQ_test=[]
#list_result_test=[]
list_two_tailed=[]
list_p_greater=[]
#list_result_test01=[]


# กำหนด % การแบ่งข้อมูล
percent_data=0.4

# ใช้ for loop สำหรับการ run ทุก replicates
for run_replicate in list_replicate:
    #DF1, DF2, SSE1, SSE2, M_SSE1, M_SSE2, GQ_test, result_test=get_result(run_replicate, percent_data)
    df1, df2, SSE1, SSE2, MSE1, MSE2, GQ_test, two_tailed, p_greater=get_result(run_replicate, percent_data)
    list_df1.append(df1)
    list_SSE1.append(SSE1)
    list_df2.append(df2)
    list_SSE2.append(SSE2)
    list_MSE1.append(MSE1)
    list_MSE2.append(MSE2)
    list_GQ_test.append(GQ_test)
    #list_result_test.append(result_test)
    list_two_tailed.append(two_tailed)
    list_p_greater.append(p_greater)
    #list_result_test01.append(result_test01)

In [9]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
result=pd.DataFrame({"Replicate":list_replicate, "df1":list_df1, "df2":list_df2, "SSE1":list_SSE1,
                     "SSE2":list_SSE2, "MSE1":list_MSE1, "MSE2":list_MSE2,
                     "GQ_test":list_GQ_test, "two_tailed":list_two_tailed, "greater":list_p_greater})
result.set_index(['Replicate'], inplace=True)
result=result[(result["two_tailed"]<=1) & (result["greater"]<=1)]
result["Result_test"]=result["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")

result.astype(str)

           df1  df2                SSE1                SSE2                MSE1                 MSE2             GQ_test              two_tailed             greater                       Result_test
Replicate
1.0        4.0  4.0  118.15241261583091  0.8408417226429173  29.538103153957728  0.21021043066072934  140.51682907034697   0.0002981839996427649  0.9998509080001786  Reject005=0 : Heteroscedasticity
2.0        4.0  4.0   88.11192923453602   6.034504656171266  22.027982308634005   1.5086261640428165    14.6013524315417    0.023597206703196205  0.9882013966484019  Reject005=0 : Heteroscedasticity
5.0        4.0  4.0   33.05457881416663  28.360314207308786   8.263644703541658   7.0900785518271965  1.1655223060133826      0.8855703593867839  0.5572148203066081    Reject005=1 : Homoscedasticity
9.0        4.0  4.0   6.850270285294751  2.1112945599913058  1.7125675713236876   0.5278236399978264  3.2445829279846956      0.2807219380165493  0.8596390309917253    Reject005=1 : Homoscedasticity
10.0       4.0  4.0  18.287962604457153   5.053292983109125   4.571990651114288   1.2633232457772812   3.619018858709667     0.24063438302175366  0.8796828084891232    Reject005=1 : Homoscedasticity
...        ...  ...                 ...                 ...                 ...                  ...                 ...                     ...                 ...                               ...
991.0      4.0  4.0   78.54277702059657   4.989804786749794  19.635694255149144   1.2474511966874484  15.740651263384782    0.020556906001311326  0.9897215469993443  Reject005=0 : Heteroscedasticity
992.0      4.0  4.0   50.07930392234171  0.5506802686880441  12.519825980585427  0.13767006717201102   90.94079953445949   0.0007046511056139071   0.999647674447193  Reject005=0 : Heteroscedasticity
993.0      4.0  4.0    9470.70599799855   8.502747790159642  2367.6764994996374   2.1256869475399105  1113.8406350190864   4.824650826629195e-06  0.9999975876745867  Reject005=0 : Heteroscedasticity
997.0      4.0  4.0  434.25834206521677  17.637579484971642  108.56458551630419   4.4093948712429105   24.62119830191172    0.008902302757549663  0.9955488486212252  Reject005=0 : Heteroscedasticity
999.0      4.0  4.0   543.9858167777654  0.7861721006324567  135.99645419444136  0.19654302515811417   691.9424084626531  1.2483574011179499e-05  0.9999937582129944  Reject005=0 : Heteroscedasticity

[504 rows x 10 columns]

In [10]:
# สร้างตารางผลลัพธ์
alpha = 0.05
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
result=pd.DataFrame({"Replicate":list_replicate, "df1":list_df1, "df2":list_df2, "SSE1":list_SSE1,
                     "SSE2":list_SSE2, "MSE1":list_MSE1, "MSE2":list_MSE2,
                     "GQ_test":list_GQ_test, "two_tailed":list_two_tailed, "greater":list_p_greater})
result.set_index(['Replicate'], inplace=True)

result['two_tailed_new']=result[["two_tailed","greater"]].apply(lambda value: value[0] if value[0]<0.5 else 2*value[1], axis=1)
result["Result_test"]=result["two_tailed"].apply(lambda p_value: 'Reject005=0 : Heteroscedasticity' 
                                                                  if p_value < alpha else 'Reject005=1 : Homoscedasticity')
#two_tailed_new_show=two_tailed_new.drop(columns="greater")
result_show=result.drop(columns=["two_tailed", "greater"])
result_show.astype(str)

           df1  df2                SSE1                SSE2                 MSE1                 MSE2               GQ_test          two_tailed_new                       Result_test
Replicate
0.0        4.0  4.0   5.257177522673835  21.526268823273504   1.3142943806684588    5.381567205818376   0.24422149355442152     0.20091629480394346    Reject005=1 : Homoscedasticity
1.0        4.0  4.0  118.15241261583091  0.8408417226429173   29.538103153957728  0.21021043066072934    140.51682907034697   0.0002981839996427649  Reject005=0 : Heteroscedasticity
2.0        4.0  4.0   88.11192923453602   6.034504656171266   22.027982308634005   1.5086261640428165      14.6013524315417    0.023597206703196205  Reject005=0 : Heteroscedasticity
3.0        4.0  4.0   2.178060635920846   3.526033068079214   0.5445151589802115   0.8815082670198034    0.6177085109151662      0.6521236137327298    Reject005=1 : Homoscedasticity
4.0        4.0  4.0   19.18701763477544   45.02646149223099     4.79675440869386   11.256615373057748    0.4261275925065981      0.4289806403407912    Reject005=1 : Homoscedasticity
...        ...  ...                 ...                 ...                  ...                  ...                   ...                     ...                               ...
995.0      4.0  4.0   7.882383489554033   219.2118905007338   1.9705958723885082    54.80297262518345   0.03595782816136813    0.007061328342224782    Reject005=1 : Homoscedasticity
996.0      4.0  4.0  0.9648527052598767   70.82641755157394  0.24121317631496916   17.706604387893485  0.013622780010824297   0.0010740420523365909    Reject005=1 : Homoscedasticity
997.0      4.0  4.0  434.25834206521677  17.637579484971642   108.56458551630419   4.4093948712429105     24.62119830191172    0.008902302757549663  Reject005=0 : Heteroscedasticity
998.0      4.0  4.0   75.85851993169227  508.26577320013587   18.964629982923068   127.06644330003397    0.1492497113352192      0.0924316878467683    Reject005=1 : Homoscedasticity
999.0      4.0  4.0   543.9858167777654  0.7861721006324567   135.99645419444136  0.19654302515811417     691.9424084626531  1.2483574011179499e-05  Reject005=0 : Heteroscedasticity

[1000 rows x 9 columns]

In [11]:
result_show['Result_test'].value_counts()

Reject005=1 : Homoscedasticity      738
Reject005=0 : Heteroscedasticity    262
Name: Result_test, dtype: int64