<a href="https://colab.research.google.com/github/iam-fern/Research/blob/main/GQtest_Cluster.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [58]:
from sklearn.cluster import KMeans

In [59]:
df = pd.read_csv('https://github.com/iam-fern/Research/raw/main/gen_SAS.csv', index_col=['Replicate', 'no'])
df

                id       j        a  ...        E        y  Unnamed: 13
Replicate no                         ...
1.0       1.0  1.0   444.0  0.29919  ...  -297.88     7.54          NaN
          2.0  1.0   611.0  0.56787  ... -1703.41 -1309.72          NaN
          3.0  1.0  3145.0  0.73834  ...  1213.77  1668.95          NaN
          4.0  1.0  4032.0  0.12840  ...    91.70   305.60          NaN
          5.0  1.0  4175.0  0.96315  ...  -403.14   145.76          NaN
...            ...     ...      ...  ...      ...      ...          ...
NaN       NaN  NaN     NaN      NaN  ...      NaN      NaN          NaN
          NaN  NaN     NaN      NaN  ...      NaN      NaN          NaN
          NaN  NaN     NaN      NaN  ...      NaN      NaN          NaN
          NaN  NaN     NaN      NaN  ...      NaN      NaN          NaN
          NaN  NaN     NaN      NaN  ...      NaN      NaN          NaN

[3150 rows x 12 columns]

In [60]:
# ลบ  colum
df.drop(['Unnamed: 13'], axis=1, inplace=True)
df

                id       j        a  ...       x3        E        y
Replicate no                         ...
1.0       1.0  1.0   444.0  0.29919  ...  37.2578  -297.88     7.54
          2.0  1.0   611.0  0.56787  ...  23.0795 -1703.41 -1309.72
          3.0  1.0  3145.0  0.73834  ...  35.5201  1213.77  1668.95
          4.0  1.0  4032.0  0.12840  ...  21.7985    91.70   305.60
          5.0  1.0  4175.0  0.96315  ...  43.8453  -403.14   145.76
...            ...     ...      ...  ...      ...      ...      ...
NaN       NaN  NaN     NaN      NaN  ...      NaN      NaN      NaN
          NaN  NaN     NaN      NaN  ...      NaN      NaN      NaN
          NaN  NaN     NaN      NaN  ...      NaN      NaN      NaN
          NaN  NaN     NaN      NaN  ...      NaN      NaN      NaN
          NaN  NaN     NaN      NaN  ...      NaN      NaN      NaN

[3150 rows x 11 columns]

In [61]:
# ลบข้อมูลที่มี missing values
table = df.dropna()
table

                 id        j        a  ...       x3        E        y
Replicate no                           ...
1.0       1.0   1.0    444.0  0.29919  ...  37.2578  -297.88     7.54
          2.0   1.0    611.0  0.56787  ...  23.0795 -1703.41 -1309.72
          3.0   1.0   3145.0  0.73834  ...  35.5201  1213.77  1668.95
          4.0   1.0   4032.0  0.12840  ...  21.7985    91.70   305.60
          5.0   1.0   4175.0  0.96315  ...  43.8453  -403.14   145.76
...             ...      ...      ...  ...      ...      ...      ...
100.0     26.0  1.0  46183.0  0.38808  ...  10.4640   -53.99   238.96
          27.0  1.0  49111.0  0.40628  ...  26.8103    16.19   348.41
          28.0  1.0  49469.0  0.40030  ...  22.3726   389.88   714.03
          29.0  1.0  49549.0  0.10914  ...  23.0568  -256.29   -59.73
          30.0  1.0  49564.0  0.98557  ...  49.0006 -2606.61 -2008.68

[3000 rows x 11 columns]

In [62]:
table.reset_index(inplace=True)
table

      Replicate    no   id        j  ...       x2       x3        E        y
0           1.0   1.0  1.0    444.0  ...  43.4873  37.2578  -297.88     7.54
1           1.0   2.0  1.0    611.0  ...  38.4642  23.0795 -1703.41 -1309.72
2           1.0   3.0  1.0   3145.0  ...  19.3175  35.5201  1213.77  1668.95
3           1.0   4.0  1.0   4032.0  ...  35.7360  21.7985    91.70   305.60
4           1.0   5.0  1.0   4175.0  ...  14.7944  43.8453  -403.14   145.76
...         ...   ...  ...      ...  ...      ...      ...      ...      ...
2995      100.0  26.0  1.0  46183.0  ...  22.2501  10.4640   -53.99   238.96
2996      100.0  27.0  1.0  49111.0  ...  37.9048  26.8103    16.19   348.41
2997      100.0  28.0  1.0  49469.0  ...  36.6570  22.3726   389.88   714.03
2998      100.0  29.0  1.0  49549.0  ...  24.8457  23.0568  -256.29   -59.73
2999      100.0  30.0  1.0  49564.0  ...  49.7059  49.0006 -2606.61 -2008.68

[3000 rows x 13 columns]

In [63]:
table.set_index(['Replicate', 'no'], inplace=True)

In [64]:
table

                 id        j        a  ...       x3        E        y
Replicate no                           ...
1.0       1.0   1.0    444.0  0.29919  ...  37.2578  -297.88     7.54
          2.0   1.0    611.0  0.56787  ...  23.0795 -1703.41 -1309.72
          3.0   1.0   3145.0  0.73834  ...  35.5201  1213.77  1668.95
          4.0   1.0   4032.0  0.12840  ...  21.7985    91.70   305.60
          5.0   1.0   4175.0  0.96315  ...  43.8453  -403.14   145.76
...             ...      ...      ...  ...      ...      ...      ...
100.0     26.0  1.0  46183.0  0.38808  ...  10.4640   -53.99   238.96
          27.0  1.0  49111.0  0.40628  ...  26.8103    16.19   348.41
          28.0  1.0  49469.0  0.40030  ...  22.3726   389.88   714.03
          29.0  1.0  49549.0  0.10914  ...  23.0568  -256.29   -59.73
          30.0  1.0  49564.0  0.98557  ...  49.0006 -2606.61 -2008.68

[3000 rows x 11 columns]

In [65]:
# แสดงค่าของ Replicate ที่ 1.0
new_table = table.loc[1.0]
new_table

       id        j        a        b  ...       x2       x3        E        y
no                                    ...
1.0   1.0    444.0  0.29919  0.83718  ...  43.4873  37.2578  -297.88     7.54
2.0   1.0    611.0  0.56787  0.71160  ...  38.4642  23.0795 -1703.41 -1309.72
3.0   1.0   3145.0  0.73834  0.23294  ...  19.3175  35.5201  1213.77  1668.95
4.0   1.0   4032.0  0.12840  0.64340  ...  35.7360  21.7985    91.70   305.60
5.0   1.0   4175.0  0.96315  0.11986  ...  14.7944  43.8453  -403.14   145.76
6.0   1.0   5338.0  0.76944  0.75934  ...  40.3737  41.4802  -137.71   356.92
7.0   1.0   6621.0  0.05064  0.15200  ...  16.0800  43.0904  -137.20    47.23
8.0   1.0   9589.0  0.40406  0.28682  ...  21.4727  18.2883  -111.47   194.92
9.0   1.0   9642.0  0.60466  0.91753  ...  46.7013  10.0734   507.98   911.62
10.0  1.0  10528.0  0.15645  0.51143  ...  30.4570  14.8377   212.46   425.33
11.0  1.0  11117.0  0.30813  0.92043  ...  46.8170  22.6720  -156.03   141.71
12.0  1.0  12400.0  0.73603  0.71343  ...  38.5371  48.1320 -2329.98 -1843.90
13.0  1.0  12522.0  0.79886  0.52487  ...  30.9948  11.8191 -1087.40  -620.04
14.0  1.0  17390.0  0.91533  0.82689  ...  43.0757  47.9272 -3389.53 -2827.39
15.0  1.0  19276.0  0.46434  0.44069  ...  27.6276  45.4201  -216.96   146.83
16.0  1.0  20825.0  0.71482  0.63640  ...  35.4561  18.6569 -1699.77 -1254.72
17.0  1.0  22501.0  0.96097  0.62880  ...  35.1518  21.3773  -929.50  -383.58
18.0  1.0  23281.0  0.85798  0.41870  ...  26.7478  26.8513  2767.12  3268.91
19.0  1.0  23385.0  0.70108  0.97359  ...  48.9435  13.3769 -1280.56  -832.81
20.0  1.0  27395.0  0.19511  0.97571  ...  49.0283  39.6073   -94.59   177.09
21.0  1.0  27582.0  0.76151  0.22916  ...  19.1665  15.7595   -46.55   397.98
22.0  1.0  31229.0  0.82012  0.10932  ...  14.3727  45.4436 -1818.19 -1325.33
23.0  1.0  31478.0  0.92934  0.64168  ...  35.6673  28.0246 -1452.93  -912.50
24.0  1.0  32521.0  0.67025  0.77900  ...  41.1599  48.3695 -2473.28 -2010.65
25.0  1.0  35132.0  0.78497  0.57425  ...  32.9699  44.5579 -3309.66 -2813.14
26.0  1.0  37070.0  0.59586  0.96391  ...  48.5566  12.1140  -210.69   193.32
27.0  1.0  39007.0  0.22566  0.44014  ...  27.6057  11.7029  -368.46  -133.89
28.0  1.0  40703.0  0.66781  0.51778  ...  30.7111  42.8235 -1086.16  -640.50
29.0  1.0  42870.0  0.63614  0.67139  ...  36.8558  12.1551   -37.26   371.21
30.0  1.0  48424.0  0.78959  0.53915  ...  31.5660  32.6206 -1845.73 -1360.71

[30 rows x 11 columns]

In [66]:
# เรียง data จากน้อยไปมากตาม x1
new_table_sort = new_table.sort_values('x1')
new_table_sort

       id        j        a        b  ...       x2       x3        E        y
no                                    ...
7.0   1.0   6621.0  0.05064  0.15200  ...  16.0800  43.0904  -137.20    47.23
4.0   1.0   4032.0  0.12840  0.64340  ...  35.7360  21.7985    91.70   305.60
10.0  1.0  10528.0  0.15645  0.51143  ...  30.4570  14.8377   212.46   425.33
20.0  1.0  27395.0  0.19511  0.97571  ...  49.0283  39.6073   -94.59   177.09
27.0  1.0  39007.0  0.22566  0.44014  ...  27.6057  11.7029  -368.46  -133.89
1.0   1.0    444.0  0.29919  0.83718  ...  43.4873  37.2578  -297.88     7.54
11.0  1.0  11117.0  0.30813  0.92043  ...  46.8170  22.6720  -156.03   141.71
8.0   1.0   9589.0  0.40406  0.28682  ...  21.4727  18.2883  -111.47   194.92
15.0  1.0  19276.0  0.46434  0.44069  ...  27.6276  45.4201  -216.96   146.83
2.0   1.0    611.0  0.56787  0.71160  ...  38.4642  23.0795 -1703.41 -1309.72
26.0  1.0  37070.0  0.59586  0.96391  ...  48.5566  12.1140  -210.69   193.32
9.0   1.0   9642.0  0.60466  0.91753  ...  46.7013  10.0734   507.98   911.62
29.0  1.0  42870.0  0.63614  0.67139  ...  36.8558  12.1551   -37.26   371.21
28.0  1.0  40703.0  0.66781  0.51778  ...  30.7111  42.8235 -1086.16  -640.50
24.0  1.0  32521.0  0.67025  0.77900  ...  41.1599  48.3695 -2473.28 -2010.65
19.0  1.0  23385.0  0.70108  0.97359  ...  48.9435  13.3769 -1280.56  -832.81
16.0  1.0  20825.0  0.71482  0.63640  ...  35.4561  18.6569 -1699.77 -1254.72
12.0  1.0  12400.0  0.73603  0.71343  ...  38.5371  48.1320 -2329.98 -1843.90
3.0   1.0   3145.0  0.73834  0.23294  ...  19.3175  35.5201  1213.77  1668.95
21.0  1.0  27582.0  0.76151  0.22916  ...  19.1665  15.7595   -46.55   397.98
6.0   1.0   5338.0  0.76944  0.75934  ...  40.3737  41.4802  -137.71   356.92
25.0  1.0  35132.0  0.78497  0.57425  ...  32.9699  44.5579 -3309.66 -2813.14
30.0  1.0  48424.0  0.78959  0.53915  ...  31.5660  32.6206 -1845.73 -1360.71
13.0  1.0  12522.0  0.79886  0.52487  ...  30.9948  11.8191 -1087.40  -620.04
22.0  1.0  31229.0  0.82012  0.10932  ...  14.3727  45.4436 -1818.19 -1325.33
18.0  1.0  23281.0  0.85798  0.41870  ...  26.7478  26.8513  2767.12  3268.91
14.0  1.0  17390.0  0.91533  0.82689  ...  43.0757  47.9272 -3389.53 -2827.39
23.0  1.0  31478.0  0.92934  0.64168  ...  35.6673  28.0246 -1452.93  -912.50
17.0  1.0  22501.0  0.96097  0.62880  ...  35.1518  21.3773  -929.50  -383.58
5.0   1.0   4175.0  0.96315  0.11986  ...  14.7944  43.8453  -403.14   145.76

[30 rows x 11 columns]

In [67]:
new_table_sort.reset_index(inplace=True)
new_table_sort

      no   id        j        a  ...       x2       x3        E        y
0    7.0  1.0   6621.0  0.05064  ...  16.0800  43.0904  -137.20    47.23
1    4.0  1.0   4032.0  0.12840  ...  35.7360  21.7985    91.70   305.60
2   10.0  1.0  10528.0  0.15645  ...  30.4570  14.8377   212.46   425.33
3   20.0  1.0  27395.0  0.19511  ...  49.0283  39.6073   -94.59   177.09
4   27.0  1.0  39007.0  0.22566  ...  27.6057  11.7029  -368.46  -133.89
5    1.0  1.0    444.0  0.29919  ...  43.4873  37.2578  -297.88     7.54
6   11.0  1.0  11117.0  0.30813  ...  46.8170  22.6720  -156.03   141.71
7    8.0  1.0   9589.0  0.40406  ...  21.4727  18.2883  -111.47   194.92
8   15.0  1.0  19276.0  0.46434  ...  27.6276  45.4201  -216.96   146.83
9    2.0  1.0    611.0  0.56787  ...  38.4642  23.0795 -1703.41 -1309.72
10  26.0  1.0  37070.0  0.59586  ...  48.5566  12.1140  -210.69   193.32
11   9.0  1.0   9642.0  0.60466  ...  46.7013  10.0734   507.98   911.62
12  29.0  1.0  42870.0  0.63614  ...  36.8558  12.1551   -37.26   371.21
13  28.0  1.0  40703.0  0.66781  ...  30.7111  42.8235 -1086.16  -640.50
14  24.0  1.0  32521.0  0.67025  ...  41.1599  48.3695 -2473.28 -2010.65
15  19.0  1.0  23385.0  0.70108  ...  48.9435  13.3769 -1280.56  -832.81
16  16.0  1.0  20825.0  0.71482  ...  35.4561  18.6569 -1699.77 -1254.72
17  12.0  1.0  12400.0  0.73603  ...  38.5371  48.1320 -2329.98 -1843.90
18   3.0  1.0   3145.0  0.73834  ...  19.3175  35.5201  1213.77  1668.95
19  21.0  1.0  27582.0  0.76151  ...  19.1665  15.7595   -46.55   397.98
20   6.0  1.0   5338.0  0.76944  ...  40.3737  41.4802  -137.71   356.92
21  25.0  1.0  35132.0  0.78497  ...  32.9699  44.5579 -3309.66 -2813.14
22  30.0  1.0  48424.0  0.78959  ...  31.5660  32.6206 -1845.73 -1360.71
23  13.0  1.0  12522.0  0.79886  ...  30.9948  11.8191 -1087.40  -620.04
24  22.0  1.0  31229.0  0.82012  ...  14.3727  45.4436 -1818.19 -1325.33
25  18.0  1.0  23281.0  0.85798  ...  26.7478  26.8513  2767.12  3268.91
26  14.0  1.0  17390.0  0.91533  ...  43.0757  47.9272 -3389.53 -2827.39
27  23.0  1.0  31478.0  0.92934  ...  35.6673  28.0246 -1452.93  -912.50
28  17.0  1.0  22501.0  0.96097  ...  35.1518  21.3773  -929.50  -383.58
29   5.0  1.0   4175.0  0.96315  ...  14.7944  43.8453  -403.14   145.76

[30 rows x 12 columns]

In [68]:
new_table_sort.drop(['no', 'id', 'j', 'a', 'b', 'c', 'z', 'E'], axis=1, inplace=True)
new_table_sort

         x1       x2       x3        y
0   12.0258  16.0800  43.0904    47.23
1   15.1362  35.7360  21.7985   305.60
2   16.2579  30.4570  14.8377   425.33
3   17.8044  49.0283  39.6073   177.09
4   19.0262  27.6057  11.7029  -133.89
5   21.9677  43.4873  37.2578     7.54
6   22.3253  46.8170  22.6720   141.71
7   26.1626  21.4727  18.2883   194.92
8   28.5738  27.6276  45.4201   146.83
9   32.7147  38.4642  23.0795 -1309.72
10  33.8343  48.5566  12.1140   193.32
11  34.1865  46.7013  10.0734   911.62
12  35.4456  36.8558  12.1551   371.21
13  36.7126  30.7111  42.8235  -640.50
14  36.8101  41.1599  48.3695 -2010.65
15  38.0431  48.9435  13.3769  -832.81
16  38.5929  35.4561  18.6569 -1254.72
17  39.4410  38.5371  48.1320 -1843.90
18  39.5337  19.3175  35.5201  1668.95
19  40.4605  19.1665  15.7595   397.98
20  40.7776  40.3737  41.4802   356.92
21  41.3990  32.9699  44.5579 -2813.14
22  41.5834  31.5660  32.6206 -1360.71
23  41.9544  30.9948  11.8191  -620.04
24  42.8048  14.3727  45.4436 -1325.33
25  44.3193  26.7478  26.8513  3268.91
26  46.6134  43.0757  47.9272 -2827.39
27  47.1737  35.6673  28.0246  -912.50
28  48.4389  35.1518  21.3773  -383.58
29  48.5260  14.7944  43.8453   145.76

In [69]:
new_table_sort.head()

        x1       x2       x3       y
0  12.0258  16.0800  43.0904   47.23
1  15.1362  35.7360  21.7985  305.60
2  16.2579  30.4570  14.8377  425.33
3  17.8044  49.0283  39.6073  177.09
4  19.0262  27.6057  11.7029 -133.89

In [70]:
new_table_sort.y.unique()

array([   47.23,   305.6 ,   425.33,   177.09,  -133.89,     7.54,
         141.71,   194.92,   146.83, -1309.72,   193.32,   911.62,
         371.21,  -640.5 , -2010.65,  -832.81, -1254.72, -1843.9 ,
        1668.95,   397.98,   356.92, -2813.14, -1360.71,  -620.04,
       -1325.33,  3268.91, -2827.39,  -912.5 ,  -383.58,   145.76])

In [118]:
# แบ่งข้อมูลออกเป็น 2 กลุ่มด้วย k-mean
x = new_table_sort[["x1", "x2", "x3"]]
km = KMeans(n_clusters=2)
km.fit(x)
y_kmeans = km.predict(x)
y_kmeans

array([1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1], dtype=int32)

In [124]:
import array as arr
from array import *
import csv

In [115]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey